# Generated by Django 3.1.7 on 2021-02-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telephone', models.CharField(max_length=100)),
                ('introduction', models.CharField(blank=True, max_length=255)),
                ('personality', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=30)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('structure', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('ethnicity', models.CharField(blank=True, max_length=30)),
                ('language', models.CharField(blank=True, max_length=30)),
                ('sexuality', models.CharField(blank=True, max_length=30)),
                ('has_children', models.BooleanField(default=False)),
                ('is_single', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('is_smoker', models.BooleanField(default=False)),
                ('is_drinker', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('has_pets', models.BooleanField(default=False)),
                ('living', models.CharField(blank=True, max_length=30)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('career', models.CharField(blank=True, max_length=255)),
                ('facebook', models.CharField(blank=True, max_length=255)),
                ('twitter', models.CharField(blank=True, max_length=255)),
                ('instagram', models.CharField(blank=True, max_length=255)),
                ('linkedin', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField()),
            ],
        ),
    ]
