# Generated by Django 3.1.7 on 2021-02-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210227_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
